### ISSUE TITLE
html태그 lang 속성

### ISSUE THREAD

**Issue by ImChangGyu** [SeoJumee/toss-cloneCoding#1]
https://github.com/SeoJumee/toss-cloneCoding/blob/44ccfe472a68eff38a45260cbb8b51e1cfa24a5e/index.html#L2

한국어로 구성된 사이트는 웹 접근성을 위해 en으로 두는것보다 ko로 변경하는게 좋습니다!
[html태그 lang 속성](https://mygumi.tistory.com/52)
위의 글을 참고해보시길 바라겠습니다!

**Comment by SeoJumee** [comment]
확인 이후 수정했습니다! 피드백 해주셔서 감사합니다.
